export const fixStatus = [
    { name: "TBD", label: "T não definido", classNames: "hidden" },
    { name: "NS", label: "Não Iniciado", classNames: "hidden" },
    { name: "1H", label: "1ºT", classNames: "" },
    { name: "HT", label: "Intervalo", classNames: "" },
    { name: "2H", label: "2ºT", classNames: "" },
    { name: "ET", label: "Prolongamento", classNames: "" },
    { name: "Q", label: "Penalidade em andamento", classNames: "" },
    { name: "FT", label: "Partida terminada", classNames: "" },
    { name: "AET", label: "Partida terminada após prolongamento", classNames: "" },
    { name: "PEN", label: "Partida terminada após pênalti", classNames: "" },
    { name: "BT", label: "T.Pausa", classNames: "" },
    { name: "P", label: "Pausa", classNames: "" },
    { name: "SUSP", label: "Suspenso", classNames: "hidden" },
    { name: "INT", label: "Interrompido", classNames: "" },
    { name: "PST", label: "Adiado", classNames: "" },
    { name: "CANC", label: "Cancelado", classNames: "" },
    { name: "ABD", label: "Abandonado", classNames: "" },
    { name: "AWD", label: "Perda Técnica", classNames: "" },
    { name: "WO", label: "Vitória Fácil", classNames: "" },
    { name: "LIVE", label: "Ao vivo", classNames: "text-red-600" }
]