export const oddBets = [
    {id: 1, name: 'Vencedor da partida'},
    {id: 2, name: 'Casa / Fora'},
    {id: 3, name: 'Vencedor 2T'},
    {id: 5, name: 'Acima/Abaixo'},
    {id: 6, name: 'Acima/Abaixo - 1T'},
    {id: 8, name: 'Ambas equipes marcam'},
    {id: 10, name: 'Pontos Exatos'},
    {id: 12, name: 'Chace dupla'},
    {id: 16, name: 'Casa - Total'},
    {id: 17, name: 'Fora - Total'},
    {id: 20, name: 'Dupla Chance - 1T'},
    {id: 21, name: 'Par/Impar'},
    {id: 22, name: 'Par/Impar - 1T'},
    {id: 24, name: 'Ambas Equipes marcam'},
    {id: 25, name: 'Total de gols'},
    {id: 31, name: 'Pontos Exatos - 1T'},
    {id: 33, name: 'Dupla Chance - 2T'},
    {id: 34, name: 'Ambas Equipes Marcam - 1T'},
    {id: 62, name: 'Pontos Exatos - 2T'},
    {id: 43, name: 'Casa - Total de gols'},
    {id: 44, name: 'Fora - Total de gols'},
]