export const oddBets = [
    {id: 1, name: 'Vencedor do encontro'},
    {id: 2, name: 'Casa / Fora'},
    {id: 3, name: 'Vencedor Segundo-tempo'},
    {id: 5, name: 'Gols Acima/Abaixo'},
    {id: 6, name: 'Gols Acima/Abaixo - Primeiro Tempo'},
    {id: 8, name: 'Ambas equipes marcam'},
    {id: 10, name: 'Pontos Exatos'},
    {id: 12, name: 'Chace dupla'},
    {id: 16, name: 'Casa - Total'},
    {id: 17, name: 'Fora - Total'},
    {id: 20, name: 'Dupla Chance - Primeiro Tempo'},
    {id: 21, name: 'Par/Impar'},
    {id: 22, name: 'Par/Impar - Primeiro Tempo'},
    {id: 24, name: 'Resultado / Ambas Equipes marcam'},
    {id: 25, name: 'Resultado / Total de gols'},
    {id: 31, name: 'Pontos Exatos - Primeiro Tempo'},
    {id: 33, name: 'Dupla Chance - Segundo Tempo'},
    {id: 34, name: 'Ambas Equipes Marcam - Primeiro Tempo'},
    {id: 62, name: 'Pontos Exatos - Segundo Tempo'},
    {id: 43, name: 'Casa - Total de gols'},
    {id: 44, name: 'Fora - Total de gols'},
]